apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cpngz0i91-nodejs-gitops
  description: This is GitOps manifest for cpngz0i91-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=cpngz0i91-nodejs
    backstage.io/kubernetes-id: cpngz0i91-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: cpngz0i91-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cpngz0i91-nodejs
